[project]
name = "firebuster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-security>=0.1.0",
    "fastapi[standard]>=0.136.1",
    "frcm",
    "pandas>=3.0.1",
    "paho-mqtt>=2.1.0",
    "requests>=2.32.0",
    "python-decouple>=3.8",
    "python-keycloak>=7.1.1",
    "uvicorn>=0.46.0",
    "sqlalchemy>=2.0.48",
    "alembic>=1.18.4",
    "psycopg2-binary>=2.9.12",
    "sqlmodel>=0.0.37",
]

[tool.uv.sources]
frcm = { git = "https://github.com/selabhvl/dynamic-frcm-simple.git" }

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
