#this runs whenever docker-compose.yml is updated
name: Docker compose updated

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - 'docker-compose.yml'
  workflow_dispatch: #for triggering manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Copy file via SSH
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.FIREBUSTER_IP}}
          username: ${{secrets.FIREBUSTER_USER}}
          key: ${{secrets.FIREBUSTER_SERVER_ACCESS}}
          source: "compose.yml"
          target: "~/firebuster-compose"

      - name: Refresh Docker
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.FIREBUSTER_IP}}
          username: ${{ secrets.FIREBUSTER_USER }}
          key: ${{ secrets.FIREBUSTER_SERVER_ACCESS }}
          script: |
            cd ~/firebuster-compose
            sudo docker compose pull
            sudo docker compose up -d
