name: Deploy

on:
  #push:
  #  branches: [main]
  workflow_dispatch: #for triggering manually

jobs:
  deploy:
    runs-on: ubuntu-24.04
    
    
    steps:
      #connection test
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.FIREBUSTER_IP }}
          username: deploy
          key: ${{ secrets.SSH_DEPLOY }}
          script: echo "Deploy triggered"
      
      #do the work
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Copy file via SSH
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.FIREBUSTER_IP}}
          username: deploy
          key: ${{ secrets.SSH_DEPLOY }}
          source: "compose.prod.yml"
          target: "/home/deploy/firebuster-compose-test"
      
      - name: Refresh Docker
        uses: appleboy/ssh-action@v1.2.5
        with: 
          host: ${{ secrets.FIREBUSTER_IP }}
          username: deploy
          key: ${{ secrets.SSH_DEPLOY }}
          script: /home/deploy/deploy.sh