name: Deploy

on:
  #push:
  #  branches: [main]
  workflow_dispatch: #for triggering manually

jobs:
  deploy:
    runs-on: ubuntu-24.04
    
    #connection test
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.FIREBUSTER_IP }}
          username: deploy
          key: ${{ secrets.SSH_DEPLOY }}
          script: echo "Deploy triggered"
      
      - name: Copy file via SSH
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.FIREBUSTER_IP}}
          username: deploy
          key: ${{ secrets.SSH_DEPLOY }}
          source: "compose.prod.yml"
          target: "~/firebuster-compose-test"